# Generated by Django 3.2.18 on 2023-04-20 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balances', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='like_users',
            field=models.ManyToManyField(related_name='like_balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
