# Generated by Django 3.2.18 on 2023-04-20 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0004_balance_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
